<Project>

	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<Product>osu! 音乐播放器</Product>
		<Company>OsuMusicPlayer</Company>
		<AssemblyVersion>1.0.0</AssemblyVersion>
		<FileVersion>1.0.0</FileVersion>
		<InformationalVersion>1.0.0</InformationalVersion>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="System" />
		<Using Include="System.Collections.Generic" />
		<Using Include="System.IO" />
		<Using Include="System.Linq" />
		<Using Include="System.Threading" />
		<Using Include="System.Threading.Tasks" />
	</ItemGroup>

</Project>
